//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace home.insurance.cn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_ItemInfo
    {
        public int ID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<byte> Channel { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductUrl { get; set; }
        public string ProductPicUrl { get; set; }
        public string ProductCompany { get; set; }
        public Nullable<decimal> StandardPice { get; set; }
        public Nullable<int> BuyNumber { get; set; }
        public Nullable<decimal> AmountPayable { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public Nullable<byte> PayType { get; set; }
        public string Memo { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> CreateMemberID { get; set; }
        public string CreateMobile { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> EffectiveBeginDate { get; set; }
        public Nullable<System.DateTime> EffectiveEndDate { get; set; }
        public string ProductType { get; set; }
        public string ProductScope { get; set; }
        public string ProductTerm { get; set; }
        public string ProductContent { get; set; }
        public string ProductTip { get; set; }
        public Nullable<decimal> ProductStandardPice { get; set; }
        public string Beneficiary { get; set; }
        public string DeliveryType { get; set; }
        public Nullable<int> DayNum { get; set; }
        public string ProductCode { get; set; }
        public Nullable<System.DateTime> ProductStartDate { get; set; }
        public Nullable<System.DateTime> ProductEndDate { get; set; }
        public string ProductJourney { get; set; }
        public string ProductProposalPlan { get; set; }
        public Nullable<byte> ProductYearFlag { get; set; }
        public string ProductSecurityProjects { get; set; }
    
        public virtual BaseInfo_UserInfo BaseInfo_UserInfo { get; set; }
        public virtual Order_BaseInfo Order_BaseInfo { get; set; }
    }
}
