//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace home.insurance.cn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_BaseInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_BaseInfo()
        {
            this.Order_ItemInfo = new HashSet<Order_ItemInfo>();
        }
    
        public int ID { get; set; }
        public Nullable<byte> Channel { get; set; }
        public Nullable<decimal> AmountPayable { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public Nullable<byte> Version { get; set; }
        public string Memo { get; set; }
        public Nullable<byte> Status { get; set; }
        public string CreateMemberPhone { get; set; }
        public Nullable<int> CreateMemberID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Code { get; set; }
    
        public virtual BaseInfo_UserInfo BaseInfo_UserInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_ItemInfo> Order_ItemInfo { get; set; }
    }
}
