//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace home.insurance.cn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Beneficiary
    {
        public int ID { get; set; }
        public Nullable<int> InsuredPersonID { get; set; }
        public Nullable<int> OrderItemID { get; set; }
        public string RelationWithInsurant { get; set; }
        public string BenifyName { get; set; }
        public string IdentifyType { get; set; }
        public string IdentifyNumber { get; set; }
        public string Sex { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<decimal> Quantity { get; set; }
    
        public virtual Order_InsuredPerson Order_InsuredPerson { get; set; }
        public virtual Order_ItemInfo Order_ItemInfo { get; set; }
    }
}
